database=postgres
spring.datasource.url=${vcap.services.petclinic-db.credentials.jdbcUrl:jdbc:postgresql://localhost/petclinic}
spring.datasource.username=${vcap.services.petclinic-db.credentials.username:petclinic}
spring.datasource.password=${vcap.services.petclinic-db.credentials.password:petclinic}
spring.datasource.name=${vcap.services.petclinic-db.credentials.name:petclinic}

spring.sql.init.mode=always
